version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 40
    commit-message:
      prefix: "dependencies(gha)"
    labels:
      - "CI/CD"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 40
    commit-message:
      prefix: "dependencies(npm)"
    labels:
      - "npm"
      - "dependencies"
