changelog:
  categories:
    - title: ':newspaper: Features'
      labels:
        - '*'
      exclude:
        labels:
          - bug
          - dependencies
          - internal improvement
          - release
    - title: ':wrench: Bug fixes'
      labels:
        - bug
    - title: ':label: :green_circle: GtiHub Actions task dependencies'
      labels:
        - CI/CD
    - title: ':label: :white_circle: npm package dependencies'
      labels:
        - npm
    - title: ':label: Other dependencies'
      labels:
        - dependencies
      exclude:
        labels:
          - CI/CD
          - npm
    - title: ':lollipop: improvements in development'
      labels:
        - internal improvement