name: "ドキュメントのLint"
description: "ドキュメントをLintします。"

runs:
  using: "composite"
  steps:
    - name: Node.js のセットアップ
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: npm パッケージのインストール
      shell: bash
      run: npm ci

    - name: Linter の処理開始
      shell: bash
      run: echo '# Linter Result :newspaper:' >> $GITHUB_STEP_SUMMARY

    - name: Markdownlint の実行
      id: run-markdownlint
      continue-on-error: true
      shell: bash
      run: |
        echo '## Markdownlint Result' >> $GITHUB_STEP_SUMMARY
        npx markdownlint-cli2 --config .markdownlint-cli2.jsonc >& markdownlint-result.txt
        echo ':heavy_check_mark: Markdownlint に成功しました。' >> $GITHUB_STEP_SUMMARY

    - name: Markdownlint 失敗時の結果表示
      shell: bash
      if: ${{ steps.run-markdownlint.outcome == 'failure' }}
      run: |
        echo ':x: Markdownlint に失敗しました。  ' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat markdownlint-result.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo 'LINT_STATUS=Error' >> $GITHUB_ENV

    - name: textlint の実行
      shell: bash
      run: |
        echo '## textlint Result' >> $GITHUB_STEP_SUMMARY
        npx textlint README.md docs --output-file textlint-result.txt --format compact
        if [ -f textlint-result.txt ]; then
          echo ':x: textlint に失敗しました。  ' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat textlint-result.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo 'LINT_STATUS=Error' >> $GITHUB_ENV
        else
          echo ':heavy_check_mark: textlint に成功しました。' >> $GITHUB_STEP_SUMMARY
        fi

    - name: Lint 結果の確認
      shell: bash
      if: ${{ env.LINT_STATUS == 'Error' }}
      run: exit 1
