gitignore: true

line-length:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  code_blocks: false
  tables: false
  headings: true
  strict: false
  stern: false

ol-prefix:
  style: "one"
ul-style:
  style: "dash"

ol-indent:
  indent: 4
ul-indent:
  indent: 4

# In the document writing environment, I want to use multiple "#" (for generating a table of contents).
# ドキュメント執筆環境では「#」を複数個使いたい（目次生成のため）。
MD025: false

# Since there is a cover, do not include a heading at the beginning of the document.
# 表紙があるため、ドキュメントの先頭には見出しを入れない。
MD041: false

# Disabled to prevent false detection of code blocks because there are times when indented text is written under bullet points.
# 箇条書きの下にインデントした文字を書くことがあるため、コードブロックの誤検知を防ぐ目的で無効化。
MD046: false
