name: ドキュメントテンプレートのビルド

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/ci-document-template-build.yml"
      - "docs/_document-template/**"
      - "docs/_shared-images/**"
      - "docs/base-style.css"
      - "package-lock.json"
      - "package.json"
  workflow_dispatch:

jobs:
  build:
    name: ドキュメントのビルド
    runs-on: windows-latest
    steps:
      - name: ブランチのチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: true

      - id: build-document
        name: ドキュメントのビルドとアップロード（PR時は除く）
        uses: ./.github/workflows/build-document
        with:
          build-script-name: "build:document-template"
